[workspace]

resolver = "3"
members = [
    "app",
    "calc",
    "models",
]

[workspace.dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
actix-web = "4"
chrono = { version = "0.4.40" }
