[package]
name = "calc"
version = "0.1.0"
edition = "2024"

[dependencies]
models = { path = "../models" }
repositories = { path = "../repositories" }
chrono.workspace = true
env_logger.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true