[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web.workspace = true
chrono.workspace = true
env_logger.workspace = true
log.workspace = true
models = { path = "../models" }
calc = { path = "../calc" }